In [11]:
import pandas as pd
import numpy as np
%matplotlib inline
import seaborn as sns
np.random.seed(29)

In [12]:
# Exercise 1. How likely is it that you roll doubles when rolling two dice?

dubs = np.random.choice(range(1,7), size = (10000,2))
dubs

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [2, 5],
       [1, 4],
       [4, 6]])

In [13]:
dubsdf = pd.DataFrame(dubs)
dubsdf

0  1
0     6  4
1     5  6
2     3  1
3     1  2
4     2  1
...  .. ..
9995  5  2
9996  3  6
9997  2  5
9998  1  4
9999  4  6

[10000 rows x 2 columns]

In [14]:
countdubs=(dubsdf[0] == dubsdf[1])
countdubs

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [15]:
countdubs.mean()

0.1709

In [17]:
# Exercise 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?


#This time, I just use size instead of .reshape(). This is my preferred method, but I'll do 
# it both ways for practice 

headsortails= np.random.choice([0,1], size=(10000,8))
headsortails


array([[0, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0]])

In [226]:
headsortails.sum(axis=1)


array([4, 4, 1, ..., 4, 5, 5])

In [18]:
headsortails.sum(axis=1) <= 3


array([ True, False, False, ...,  True, False,  True])

In [19]:
(headsortails.sum(axis=1) == 3).mean()

#Probability of getting 3 heads


0.2243

In [20]:
(headsortails.sum(axis=1) > 3).mean()

# Probability of getting more than 3 heads

0.6313

In [236]:
# I'm also finding the value of less than 3 heads so that I can check the accuracy of my 
# solution. Everything should add up to 1
(headsortails.sum(axis=1) < 3).mean()


0.1505

In [239]:
#Good to go!

(headsortails.sum(axis=1) < 3).mean()+ (headsortails.sum(axis=1) > 3).mean() + (headsortails.sum(axis=1) == 3).mean()

0.9999999999999999

In [249]:
# Exercise 3. There are approximitely 3 web development cohorts for every 1 data science 
# cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the
# odds that the two billboards I drive past both have data science students on them?

# wd = 0
# ds = 1
# rows=1000
# cols=2

billboard= np.random.choice([0,1], size = (10000, 2), p = [.75, .25])
billboard

array([[1, 1],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 1],
       [0, 0]])

In [250]:
dsboard=(billboard == 1)
dsboard

array([[ True,  True],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False,  True],
       [False, False]])

In [251]:
(dsboard.sum(axis=1) ==2).mean()

0.0621

In [252]:
(billboard.sum(axis=1)==2).mean()

0.0621

In [55]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day
# from the snack vending machine. If on monday the machine is restocked with 17 poptart 
# packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal)
# You'll need to make a judgement call on how to handle some of your values

poptartsaregross= np.random.normal(loc=3,scale=1.5,size=(1000,5))
poptartsaregross

array([[4.5385589 , 3.05444823, 4.20758969, 5.98210083, 2.57615686],
       [1.59425   , 1.5034385 , 1.47062783, 3.69443948, 4.57286714],
       [0.96432064, 3.39767175, 1.81958577, 2.1177621 , 1.88405883],
       ...,
       [2.18210518, 1.95682975, 1.99114806, 2.90565526, 3.86566791],
       [2.19730677, 2.82223309, 3.83524847, 1.9562706 , 3.02713745],
       [2.24635143, 3.56406863, 2.14699214, 2.8678356 , 3.97954274]])

In [259]:
poptartsaregross[poptartsaregross <0] = 0

In [260]:
poptartsaregross.sum(axis=1)

array([20.35885449, 12.83562295, 10.1833991 , 15.18591098, 15.94901662,
       11.35033559, 16.49888585, 16.36277275, 16.98156239, 17.48322982,
       17.61785652, 13.96159125, 18.38547862, 16.43466369, 21.46607488,
       15.3113123 , 17.0417936 , 17.86024605, 14.26777102, 11.8668304 ,
       19.0245129 , 15.2580386 , 16.48304142, 19.95278683, 14.72239252,
       16.62613736, 12.0360746 , 14.33568634, 12.88984525, 19.58633682,
       14.19897167, 15.06237217, 12.37195456, 15.9634423 , 13.83333796,
       14.73455558, 16.76213971, 17.12453963, 16.08660101, 13.02887792,
       16.45286937, 13.42447137, 17.53456224, 17.10183956, 15.7573125 ,
       13.96827154, 18.8522924 , 17.39045242, 10.61699268, 12.76882338,
       14.67108517,  8.37698694, 18.44870998, 16.14957663, 15.53540122,
        8.68794566, 12.104487  , 20.36218253, 19.44896525, 11.81996347,
       12.99704412, 14.6275384 , 11.76946727,  7.0536163 , 17.51588299,
       20.74048659, 18.28051055, 15.46855669, 17.44642397, 16.80

In [261]:
poptartsaregross.sum(axis=1) <=17

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True, False,  True, False, False,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False, False, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True,  True,
       False,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,

In [264]:
(poptartsaregross.sum(axis=1) <=17).mean()

# There's a 72% chance that I can buy a poptart Friday.

0.711

In [283]:
# Exercise 5. Compare Heights

#     Men have an average height of 178 cm and standard deviation of 8cm.
#     Women have a mean of 170, sd = 6cm.
#     Since you have means and standard deviations, you can use np.random.normal to generate observations.
#     If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

women = np.random.normal(170, 6, size=(10000))
men = np.random.normal(178, 8, size = (10000))
women

array([166.08348557, 164.03046538, 176.6224632 , ..., 171.40894964,
       178.51622464, 183.12742423])

In [281]:
men

array([174.56137057, 160.41703116, 185.00070316, ..., 190.70524344,
       166.65923064, 177.88878136])

In [284]:
(women > men).mean()

# 21% chance that the woman is taller

0.2131

In [32]:


# When installing anaconda on a student's computer, there's a 1 in 250 chance that the 
# download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has 
#an installation issue? 


#A: With 50 students, there's an 81% chance that no one has installation issues

myandacondadont= np.random.choice([0,1], size = (1000,50), p=[249/250, 1/250])
myandacondadont

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
(myandacondadont.sum(axis = 1) == 0).mean()

0.816

In [34]:
myandacondadont.sum(axis = 1) == 0

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True, False, False, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,

In [35]:
(myandacondadont.sum(axis=1)==0).mean()

0.816

In [36]:
#With 100 students?


#A: With 100 installations, there's a 66% chance of no installation errors

wantnone= np.random.choice([0,1], size = (1000,100), p=[249/250, 1/250])
wantnone

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [37]:
(wantnone.sum(axis=1)==0).mean()

0.663

In [38]:
# What is the probability that we observe an installation issue within the 
# first 150 students that download anaconda?


# A: .476 probability


unlessyougot= np.random.choice([0,1], size = (1000,150), p=[249/250, 1/250])
unlessyougot

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
(unlessyougot.sum(axis=1)>0).mean()

0.476

In [41]:
# How likely is it that 450 students all download anaconda without an issue?


# A:

installationissues_hon= np.random.choice([0,1], size = (1000,450), p=[249/250, 1/250])
installationissues_hon

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
(installationissues_hon.sum(axis=1) ==0).mean()



0.173

In [138]:
# There's a 70% chance on any given day that there will be at least one food truck at 
# Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

foodtruckfridays = np.random.choice([0,1],size = (1000,3))
foodtruckfridays

array([[1, 1, 1],
       [1, 1, 0],
       [0, 0, 0],
       ...,
       [1, 0, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [142]:
onsight = (foodtruckfridays >= .7)
onsight

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       ...,
       [ True, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [143]:
onsight.sum(axis=1)

array([3, 2, 0, 1, 2, 1, 1, 3, 0, 2, 2, 2, 2, 3, 0, 3, 0, 1, 2, 1, 2, 1,
       3, 1, 2, 0, 0, 1, 1, 1, 2, 3, 1, 0, 1, 2, 3, 0, 3, 2, 0, 1, 3, 2,
       1, 1, 0, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 1, 3,
       1, 3, 2, 1, 2, 3, 2, 3, 2, 2, 3, 0, 2, 2, 1, 2, 3, 0, 2, 1, 2, 3,
       2, 1, 3, 1, 1, 1, 2, 3, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 0, 1, 1, 2,
       2, 1, 1, 2, 1, 3, 2, 1, 2, 3, 3, 2, 3, 2, 0, 2, 2, 1, 2, 0, 3, 1,
       2, 2, 1, 2, 2, 3, 0, 0, 1, 2, 1, 1, 2, 2, 3, 1, 1, 1, 0, 1, 2, 1,
       2, 2, 2, 2, 2, 1, 1, 1, 2, 0, 1, 2, 0, 2, 1, 0, 1, 1, 1, 1, 3, 2,
       2, 1, 0, 0, 1, 1, 2, 1, 1, 3, 2, 1, 3, 2, 3, 1, 2, 1, 1, 1, 2, 1,
       2, 3, 0, 2, 3, 1, 1, 1, 2, 1, 1, 3, 2, 3, 1, 1, 1, 2, 3, 2, 3, 2,
       1, 1, 2, 1, 2, 1, 1, 1, 3, 2, 1, 0, 2, 2, 2, 2, 1, 2, 3, 1, 1, 1,
       3, 0, 0, 2, 1, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 1, 3, 2, 3, 3, 3, 1,
       1, 1, 2, 2, 0, 2, 1, 2, 3, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 0, 1, 1,
       2, 0, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1,

In [10]:
(onsight.sum(axis=1) == 1).mean()

NameError: name 'onsight' is not defined

In [198]:
# If 23 people are in the same room, what are the odds that two of them share a birthday?
# What if it's 20 people? 40?

#I need to account for all 365 days of the year, so maybe a range
goshawty= np.random.choice(range(1,366), size=(10000,23))
goshawty

array([[104, 288, 327, ..., 303, 153, 113],
       [238, 290,  73, ..., 353,   5, 282],
       [279, 148, 325, ...,  49, 203, 340],
       ...,
       [ 19,  94,  98, ..., 199,  45, 250],
       [353,  28, 178, ..., 297, 241, 343],
       [192, 172,  85, ..., 263, 150, 236]])

In [199]:
itsyourbirthday= pd.DataFrame(goshawty).nunique(axis =1)
itsyourbirthday

0       23
1       23
2       23
3       20
4       23
        ..
9995    23
9996    23
9997    22
9998    23
9999    22
Length: 10000, dtype: int64

In [204]:
(itsyourbirthday !=23).mean()

0.5054

In [195]:
wegonparty= np.random.choice(range(1,366), size=(10000,20))
wegonparty

array([[ 45, 143, 112, ...,  43, 344,  34],
       [ 83, 323, 310, ..., 226, 239, 239],
       [224, 239, 196, ...,  51, 362, 100],
       ...,
       [279, 221, 310, ..., 165,  57,  56],
       [102, 174, 182, ..., 144, 124, 251],
       [229, 329,  65, ..., 302,   2, 250]])

In [196]:
likeitsyourbday= pd.DataFrame(wegonparty).nunique(axis =1)
likeitsyourbday

0       20
1       19
2       20
3       20
4       20
        ..
9995    19
9996    20
9997    20
9998    19
9999    20
Length: 10000, dtype: int64

In [197]:
# 20 people

(likeitsyourbday != 20).mean()

0.4129

In [192]:
gonnasip = np.random.choice(range(1,366), size=(10000,40))
gonnasip

array([[351, 236, 156, ..., 329,  87, 262],
       [ 21, 198,  42, ..., 324, 285, 252],
       [ 73,  61,  46, ..., 193,  49,  13],
       ...,
       [208, 325, 235, ...,  30, 298, 210],
       [243, 154,  85, ..., 205, 258, 268],
       [262, 201, 343, ..., 219,  47, 274]])

In [193]:
bacardi = pd.DataFrame(gonnasip).nunique(axis =1)
bacardi

0       39
1       38
2       36
3       36
4       38
        ..
9995    39
9996    37
9997    40
9998    39
9999    38
Length: 10000, dtype: int64

In [194]:
#40 people:

(bacardi != 40).mean()

0.8921